### ISSUE TITLE
The Android Net8 Binding does not have the proper objects.

### ISSUE THREAD

**Issue by Elinares-82** [CleverTap/clevertap-xamarin#17] opened 2024-03-30 16:03 UTC
I'm opening a new issue since the issue #13 didn't fixed for Android.

I provided all the information in the same #13

**Comment by Anush-Shand** [comment] 2024-03-31 08:51
@Elinares-82 Are you including the clevertap dependecy using an Assembly Reference (.dll file)? If yes then the .aar file should reside in the same directory as the .dll file. This is because of the reason mentioned [here](https://learn.microsoft.com/en-us/dotnet/maui/migration/android-binding-projects?view=net-maui-8.0#embedded-jaraar-files)

You can also consider using the clevertap dependency directly from NuGet https://www.nuget.org/packages/CleverTap.DotNet.Android.Binding/

**Comment by Elinares-82** [comment] 2024-03-31 17:34
> @Elinares-82 Are you including the clevertap dependecy using an Assembly Reference (.dll file)? If yes then the .aar file should reside in the same directory as the .dll file. This is because of the reason mentioned [here](https://learn.microsoft.com/en-us/dotnet/maui/migration/android-binding-projects?view=net-maui-8.0#embedded-jaraar-files)
> 
> You can also consider using the clevertap dependency directly from NuGet https://www.nuget.org/packages/CleverTap.DotNet.Android.Binding/

Hi @Anush-Shand , I’m using the nuget instead of the DLL directly.

**Comment by Anush-Shand** [comment] 2024-04-01 06:27
@Elinares-82 
Does it work with the NuGet pkg. Please try clean and build once.
I tried using the nuget package on a fresh demo app and it works fine
<img width="1217" alt="Screenshot 2024-04-01 at 11 55 16 AM" src="https://github.com/CleverTap/clevertap-xamarin/assets/127097095/d64ebcc1-b66c-45d1-9e1a-b0e41e8e16f9">


This .dll has a smaller size than the older one because of the details mentioned [here](https://learn.microsoft.com/en-us/dotnet/maui/migration/android-binding-projects?view=net-maui-8.0#embedded-jaraar-files)

The VS solution you had attached also looks fine. The version of clevertap .aar added is old though

**Comment by Elinares-82** [comment] 2024-04-01 15:17
> @Elinares-82 Does it work with the NuGet pkg. Please try clean and build once. I tried using the nuget package on a fresh demo app and it works fine <img alt="Screenshot 2024-04-01 at 11 55 16 AM" width="1217" src="https://private-user-images.githubusercontent.com/127097095/318355056-d64ebcc1-b66c-45d1-9e1a-b0e41e8e16f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5ODQ1MzQsIm5iZiI6MTcxMTk4NDIzNCwicGF0aCI6Ii8xMjcwOTcwOTUvMzE4MzU1MDU2LWQ2NGViY2MxLWI2NmMtNDVkMS05ZTFhLWIwZTQxZThlMTZmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQxNTEwMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZWMyMzUxOWNhMDc3ZGVjMTA4YWE3MzI2YTgwNjllZDZkMGNiMzVhOWQ4NTUxZDY2M2M3NjhhZmQ2MTUxYjgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DTHVjuAsRzb6l3T1hlQKC3cKvwBo8iKdtgpgsZzRn_E">
> 
> This .dll has a smaller size than the older one because of the details mentioned [here](https://learn.microsoft.com/en-us/dotnet/maui/migration/android-binding-projects?view=net-maui-8.0#embedded-jaraar-files)
> 
> The VS solution you had attached also looks fine. The version of clevertap .aar added is old though

@Anush-Shand  thanks for your response. I'm using VS 2022 17.9.5 and using both approaches I'm getting the same result. The namespace is not being detected. Could you please use the same IDE, I assume that you are using VS Code for Mac o VS for Mac?

![image](https://github.com/CleverTap/clevertap-xamarin/assets/158092565/2967481e-27e5-4b11-b3c9-4af009edd268)

![image](https://github.com/CleverTap/clevertap-xamarin/assets/158092565/580610f9-5624-4639-b690-a437fb24401c)

![image](https://github.com/CleverTap/clevertap-xamarin/assets/158092565/b1adb636-1e64-4269-82c7-e3160801ab37)

**Comment by Anush-Shand** [comment] 2024-04-02 14:36
@Elinares-82 Currently I am using VS for mac version 17.6.10. I will try testing on other versions.
In the meantime can you try adding the Clevertap Binding as a project reference using the .dll file. Make sure to include the [clevertap .aar ](https://github.com/CleverTap/clevertap-xamarin/blob/master/clevertap-component/lib/android/clevertap-android-sdk-6.1.1.aar) in the same directory as the .dll file

**Comment by Elinares-82** [comment] 2024-04-02 20:02
> @Elinares-82 Currently I am using VS for mac version 17.6.10. I will try testing on other versions. In the meantime can you try adding the Clevertap Binding as a project reference using the .dll file. Make sure to include the [clevertap .aar ](https://github.com/CleverTap/clevertap-xamarin/blob/master/clevertap-component/lib/android/clevertap-android-sdk-6.1.1.aar) in the same directory as the .dll file

@Anush-Shand  thanks!, What I did was update my Android binding project using the latest .aar version 6.1.1 and generate the full assembly instead. I know that MAUI changed this to use the second approach but apparently there are a bug in VS 2022 since is not recognizing the namespace if the .aar is in a different file. 

Havin said this, I used the nuget for iOS that until now is working as expected, and Android is using an embedded .aar assembly. Let me know if you can test the Android nuget in VS 2022 since that I read is the VS for Mac will be retired.

Thanks again.

**Comment by Anush-Shand** [comment] 2024-04-04 08:03
@Elinares-82 It is good to hear that there are no blockers from Clevertap's side at the moment

I tried testing the issue on a different machine and I was able to reproduce the issue. 
I then added the Clevertap android dependency as an Assembly reference. Following this I removed the assembly reference and then added the Nuget package and the issue magically went away forever. Seems like some VisualStudio caching issue.
You can try the same?
It will also be helpful if you can create a dummy project where the issue is reproducible and share the zipped project

**Comment by Elinares-82** [comment] 2024-04-10 14:33
> I then added the Clevertap android dependency as an Assembly reference.

Hi @Anush-Shand ,

Yes, I did this several times, however, the project did compile since the namespace was not found. Not sure why this behavior. I'll create a new project to replicate and provide you to detect what is happening.

**Comment by Elinares-82** [comment] 2024-07-16 21:39
Hi,

Definitely compile using the nuget is not possible in VS for Windows. The nuget files are in the target folder but VS is not able to find the clasess.

![image](https://github.com/user-attachments/assets/55fc3f81-65d0-40c0-a8d2-c63985b4b3e3)

![image](https://github.com/user-attachments/assets/a56fab35-18ba-46ca-99b6-584347813b29)

**Comment by Anush-Shand** [comment] 2024-12-13 11:22
This has been fixed in Clevertap.DotNet.Android.Binding v2.0.0 
https://www.nuget.org/packages/CleverTap.DotNet.Android.Binding/

**Closed as completed by Anush-Shand** 2024-12-13 11:22 UTC
